import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex">
         
         <nav className="w-64 bg-slate-900 text-white p-6 flex flex-col gap-4 min-h-screen">
          <h2 className="text-2xl font-bold mb-8 text-amber-500"> Cinermark</h2>
          
        
          <Link href="/" className="hover:text-blue-300 transition">Inicio</Link>
          <Link href="/populares" className="hover:text-blue-300 transition">Peliculas Populares</Link>
           <Link href="/buscar" className="hover:text-blue-300 transition">Buscar</Link>
          <Link href="/mis_fav" className="hover:text-blue-300 transition">Mis favoritas</Link>
          
          <div className="mt-auto text-xs text-slate-500">
            Cinermark 
          </div>
        </nav>
        
        
        
        
        
        
        
        
        {children}

      </body>
    </html>
  );
}
